baseurl = "/"
languageCode = "en-us"
title = "Simon Says!"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/SchultenSimon"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [S.C. Schulten](http://simon-schulten.netlify.com) 2019"
