baseurl = "/"
languageCode = "en-us"
title = "Simon Says!"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 2
[[menu.main]]
    name = "Github"
    url = "https://github.com/Simon-Schulten"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [S.C. Schulten](http://simon-schulten.de) 2019 | [Impressum](http://simon-schulten.de/post/2019/02/05/impressum/)"
    author = "Simon C. Schulten"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
