---
title: Building a Website
author: Simon C. Schulten
date: '2019-06-08'
slug: operating-a-website-under-gdpr
categories: []
tags: []
---

When I decided to create a website that keeps a record of [some of the things I am interested in](http://simon-schulten.de/post/2019/02/05/inaugural-blog-post/), it became quickly apparent to me that there were many design choices to be made. Of course, having a multitude of options almost certainly means the end-product could differ enormously, not just visually but also under the hood.  

Since I will (probably!) be the only one writing for this website, I decided I do not need a fancy content management system with a fancy online collaborative writing tool. While I might end up showing some pictures (ggplot, anyone?), this is not a photography blog. Content will mainly be text and one day some file hosting (like, say, papers), so that is what the underlying system should be optimized for.  

This renders many of the for-profit systems like wordpress or squarespace needlessly powerful (e.g. I have no aspiration to start an online shop). I settled for a static html web page, mainly because there is no real need for interactive content. I am interested in interactive shiny apps, however I have not really done anything serious with shiny yet. Should I decide to do something, I will have to check how to include this in a static html site. To me the easiest way of setting up a static html web page is to use the awesome [blogdown package](https://bookdown.org/yihui/blogdown/). This approach has a couple of cool features I'd like to mention.  

First and foremost, the decision to build a static html page means the page should load really quickly. On top of this tech-specific strength, blogdown makes it simple to use pre-configured themes and adapt them to one's own needs. Blogdown is built on top of Hugo implying that any Hugo theme should work. I went with the [XMin theme](https://xmin.yihui.name/), which is pretty minimalist to begin with. This makes it even easier to digest what is going on. For example, the EU requires website operators who want to track visitors to follow General Data Protection Regulation. Yes, you read correctly: I need to comply with the infamous GDPR. As I am using blogdown and thus have total control over the source code of my website it was very easy to accomplish this. I just disabled any third party application that uses tracking technology, like Google Analytics for example. Basically, I am complying with data privacy regulation by not collecting data. This completely removes any headache of dealing with privacy regulations. The added benefit being that I can tell you this website is tracking-free.  

Secondly, blogdown gives me the ability to create content for the website using the R-Studio version of markdown: [RMarkdown](https://rmarkdown.rstudio.com/). This means I can use the same syntax for writing blogposts as for writing reproducible research reports. Plus, I can easily put in some code if I were to write about a neat package or even show off a statistical analysis. For the most part, I find markdown gets out of the way when writing, so this suits me well.  

Thirdly, maintaining a website in Rstudio is just handy. I have one application to both create content and make changes to the website layout. I can work offline and even test my changes right inside Rstudio. All files pertaining to my website live inside a Rstudio Project, so that I do not even have to change to a file manager to open another file.  

Lastly, it is easy to deploy the website through github and netlify as suggested by the official blogdown documentation. Publishing a new post or a changed layout is now as easy as the familiar add-commit-push routine. Of course, I could have also spent time figuring out how to host the page directly via github, but the process on netlify was so seamless I did not even bother. I did, however, take some time to register a custom domain name to forego the .netlify.com or .github.io addition. This worked well despite the time it takes for DNS configurations to propagate throughout the internet.  

All in all, I have really enjoyed my experience with blogdown so far. If someone asked me how to set up a website, I would point them towards blogdown - given they have at least some coding experience!
